networks:
  shared_backend:
    external: true
    name: chat_resource_backend

services:
  app:
    env_file:
      - .env
    container_name: chat-be
    restart: unless-stopped
    build: .
    ports:
      - "$PORT:$PORT"
    networks:
      - shared_backend
